In [50]:
import googlemaps
import geopy.distance
from pymongo import MongoClient
from datetime import datetime
import os
import requests
import json
import time
import pandas as pd
import folium
from dotenv import load_dotenv
load_dotenv()

True

In [51]:
##function to connect to MOngoDB
def connectCollection(database, collection):
    client = MongoClient()
    db = client[database]
    coll = db[collection]
    return db, coll

##Function to calculate distance between two points
def getLocCoord(office):
    longitude = office['longitude']
    latitude = office['latitude']
    loc = {
        'type':'Point',
        'coordinates':[longitude, latitude]
    }
    return loc

##Search places from coordinates
def nearbysearchName(query,location,radius):
    API_key = os.getenv('key')
    endpoint_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    places = []
    params = {
        'rankbydistance':"",
        'location': location,
        'radius': radius,
        'name': query,
        'key': API_key
    }
    res = requests.get(endpoint_url, params = params)
    results =  json.loads(res.content)
    places.extend(results['results'])
    return places

def nearbysearchType(query,location,radius,gtype):
    API_key = os.getenv('key')
    endpoint_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    places = []
    params = {
        'rankbydistance':"",
        'location': location,
        'radius': radius,
        'query': query,
        'type':gtype,
        'key': API_key
    }
    res = requests.get(endpoint_url, params = params)
    results =  json.loads(res.content)
    places.extend(results['results'])
    return places


## get location from places
def getLocation(result):
    location = []
    for i in range(len(result)):
        latitude = result[i]['geometry']['location']['lat']
        longitude = result[i]['geometry']['location']['lng']
        name = result[i]['name']
        address = result[i]['vicinity']
        loc = {
            'name': name,
            'address': address,
            'longitude': longitude,
            'latitude': latitude
        }
        location.append(loc)
    return location

##Function to find closest airport
def closest_airport(office,df):
    coords_off = (office.get('latitude'),office.get('longitude'))
    dist = []
    for i in range(len(df)):
        coords_air = (df.iloc[i].get('lat'),df.iloc[i].get('lon'))
        dist.append(geopy.distance.geodesic(coords_off, coords_air).km)
    return min(dist)

In [31]:
airports=pd.read_csv("./output/filtered_airports.csv")
offices=pd.read_csv("./output/filtered_offices.csv")

In [32]:
airports.iloc[0]

Unnamed: 0                                        0
code                                            ABQ
lat                                         35.0494
lon                                        -106.625
name              Albuquerque International Airport
city                                    Albuquerque
state                                    New Mexico
country                               United States
woeid                                      12518564
icao                                           KABQ
direct_flights                                   41
carriers                                         25
Name: 0, dtype: object

In [33]:
print(len(offices),len(airports))
display(offices)

85 50

,Unnamed: 0,name,category,city,country,latitude,longitude,is_gaming,total_companies
0,0,Thoof,web,Austin,USA,30.268735,-97.745209,0,36
1,1,RockYou,games_video,Redwood City,USA,37.484619,-122.206893,1,23
2,2,Carbonite,network_hosting,Boston,USA,42.350571,-71.076869,0,26
3,3,oDesk,web,Redwood City,USA,37.479952,-122.178557,0,23
4,4,Bazaarvoice,software,Austin,USA,30.407545,-97.717667,0,36
...,...,...,...,...,...,...,...,...,...
80,80,Virdia,cleantech,Redwood City,USA,37.523311,-122.259154,0,23
81,81,Buzzient,enterprise,Boston,USA,42.362856,-71.083762,0,26
82,82,Nuventix,cleantech,Austin,USA,30.239229,-97.834211,0,36
83,83,Pearl Therapeutics,biotech,Redwood City,USA,37.502169,-122.217727,0,23
84,84,Spiracur,medical,Redwood City,USA,37.429834,-122.004179,0,23

In [34]:
print(offices.iloc[0])
print(airports.iloc[0])
print(closest_airport(offices.iloc[0],airports))

Unnamed: 0               0
name                 Thoof
category               web
city                Austin
country                USA
latitude           30.2687
longitude         -97.7452
is_gaming                0
total_companies         36
Name: 0, dtype: object
Unnamed: 0                                        0
code                                            ABQ
lat                                         35.0494
lon                                        -106.625
name              Albuquerque International Airport
city                                    Albuquerque
state                                    New Mexico
country                               United States
woeid                                      12518564
icao                                           KABQ
direct_flights                                   41
carriers                                         25
Name: 0, dtype: object
10.618504347609518

In [35]:
dist_airport=[]
for x in range(len(offices)):
    office=offices.iloc[x]
    dist_airport.append(closest_airport(office,airports))
print(len(dist_airport))

85

In [36]:
offices['dist_airport'] = dist_airport

In [37]:
display(offices.head())

,Unnamed: 0,name,category,city,country,latitude,longitude,is_gaming,total_companies,dist_airport
0,0,Thoof,web,Austin,USA,30.268735,-97.745209,0,36,10.618504
1,1,RockYou,games_video,Redwood City,USA,37.484619,-122.206893,1,23,21.824782
2,2,Carbonite,network_hosting,Boston,USA,42.350571,-71.076869,0,26,4.652931
3,3,oDesk,web,Redwood City,USA,37.479952,-122.178557,0,23,24.078317
4,4,Bazaarvoice,software,Austin,USA,30.407545,-97.717667,0,36,23.260582

In [15]:
starbucks =nearbysearchName('starbucks','30.268735,-98.745209',5)

print(starbucks)

[]

In [38]:
##Function to find closest airport                 
def closest_starbucks(office):
    coords_off = (office.get('latitude'),office.get('longitude'))
    coords_off2 = ("{},{}".format(coords_off[0],coords_off[1]))
    nbs_list=nearbysearchName("starbucks",coords_off2,500)
    dist = []
    a=0
    if nbs_list==[]:
        return dist.append(a)
    else:
        starbucks=pd.DataFrame(getLocation(nbs_list)).iloc[0]
        coords_str=(starbucks.get('latitude'),starbucks.get('longitude'))
        geo_dist=(geopy.distance.geodesic(coords_off, coords_str).m)
        dist.append(geo_dist)
        return dist

In [39]:
dist_starbucks=[]
for x in range(len(offices)):
    office=offices.iloc[x]
    dist_starbucks.append(closest_starbucks(office))

offices['dist_starbucks'] = dist_starbucks

display(offices)

,Unnamed: 0,name,category,city,country,latitude,longitude,is_gaming,total_companies,dist_airport,dist_starbucks
0,0,Thoof,web,Austin,USA,30.268735,-97.745209,0,36,10.618504,[223.1254528756234]
1,1,RockYou,games_video,Redwood City,USA,37.484619,-122.206893,1,23,21.824782,None
2,2,Carbonite,network_hosting,Boston,USA,42.350571,-71.076869,0,26,4.652931,[360.8002031987894]
3,3,oDesk,web,Redwood City,USA,37.479952,-122.178557,0,23,24.078317,[682.1748913747878]
4,4,Bazaarvoice,software,Austin,USA,30.407545,-97.717667,0,36,23.260582,[636.0121191626315]
...,...,...,...,...,...,...,...,...,...,...,...
80,80,Virdia,cleantech,Redwood City,USA,37.523311,-122.259154,0,23,15.519179,[658.716596872321]
81,81,Buzzient,enterprise,Boston,USA,42.362856,-71.083762,0,26,4.689089,[354.4471827895814]
82,82,Nuventix,cleantech,Austin,USA,30.239229,-97.834211,0,36,16.757988,[810.1012949623281]
83,83,Pearl Therapeutics,biotech,Redwood City,USA,37.502169,-122.217727,0,23,19.833559,None
84,84,Spiracur,medical,Redwood City,USA,37.429834,-122.004179,0,23,39.959483,None

In [27]:
print(offices.dtypes)

Unnamed: 0           int64
name                object
category            object
city                object
country             object
latitude           float64
longitude          float64
is_gaming            int64
total_companies      int64
dist_airport       float64
dist_starbucks      object
dtype: object

In [52]:
##Function to find closest whatever place we want
def closest_gtype(office,query,radius,gtype):
    coords_off = (office.get('latitude'),office.get('longitude'))
    coords_off2 = ("{},{}".format(coords_off[0],coords_off[1]))
    nbs_list=nearbysearchType(query,coords_off2,radius,gtype)
    dist = []
    a=0
    if nbs_list==[]:
        return dist.append(a)
    else:
        df=pd.DataFrame(getLocation(nbs_list)).iloc[0]
        coords_df=(df.get('latitude'),df.get('longitude'))
        geo_dist=(geopy.distance.geodesic(coords_off, coords_df).m)
        dist.append(geo_dist)
        return dist

In [53]:
## 4. Distance to Closest Vegan Restaurant
dist_vegan=[]
for x in range(len(offices)):
    office=offices.iloc[x]
    dist_vegan.append(closest_gtype(office,"vegan",500,"restaurant"))

offices['dist_vegan'] = dist_vegan

In [56]:
## 5. Distance to Closest Waldorf school
dist_school=[]
for x in range(len(offices)):
    office=offices.iloc[x]
    dist_school.append(closest_gtype(office,"waldorf",10000,"school"))

offices['dist_school'] = dist_school

ValueError: Length of values does not match length of index

In [54]:
display(offices)

,Unnamed: 0,name,category,city,country,latitude,longitude,is_gaming,total_companies,dist_airport,dist_starbucks,dist_vegan
0,0,Thoof,web,Austin,USA,30.268735,-97.745209,0,36,10.618504,[223.1254528756234],[291.990160587776]
1,1,RockYou,games_video,Redwood City,USA,37.484619,-122.206893,1,23,21.824782,None,[388.9440905173135]
2,2,Carbonite,network_hosting,Boston,USA,42.350571,-71.076869,0,26,4.652931,[360.8002031987894],[177.1146798721089]
3,3,oDesk,web,Redwood City,USA,37.479952,-122.178557,0,23,24.078317,[682.1748913747878],[133.086961980324]
4,4,Bazaarvoice,software,Austin,USA,30.407545,-97.717667,0,36,23.260582,[636.0121191626315],[421.3447482904472]
...,...,...,...,...,...,...,...,...,...,...,...,...
80,80,Virdia,cleantech,Redwood City,USA,37.523311,-122.259154,0,23,15.519179,[658.716596872321],[466.455844452992]
81,81,Buzzient,enterprise,Boston,USA,42.362856,-71.083762,0,26,4.689089,[354.4471827895814],[295.94663018755807]
82,82,Nuventix,cleantech,Austin,USA,30.239229,-97.834211,0,36,16.757988,[810.1012949623281],[236.6836293418089]
83,83,Pearl Therapeutics,biotech,Redwood City,USA,37.502169,-122.217727,0,23,19.833559,None,None
84,84,Spiracur,medical,Redwood City,USA,37.429834,-122.004179,0,23,39.959483,None,None